spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: agenda
          uri: lb://agenda
          predicates:
            - Path=/agenda/**
        - id: sala
          uri: lb://sala
          predicates:
            - Path=/sala/**
        - id: funcionario
          uri: lb://funcionario
          predicates:
            - Path=/funcionario/**
server:
  port: ${PORTA:8000}
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka